# Generated by Django 4.2.16 on 2024-10-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_permission_group_permissions_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_permissions',
            old_name='permissions',
            new_name='permission',
        ),
    ]
